name: run_local_docker

on:
  push:
  pull_request:
  schedule:
  - cron: "0 0 13 * *"

jobs:
  run_local_docker:
    runs-on: ubuntu-latest
    steps:

      - name: Free Disk Space
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true
          # all of these default to true, but feel free to set to
          # false if necessary for your workflow
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          swap-storage: true

      - uses: actions/checkout@v2

      # From https://github.com/actions/setup-java?tab=readme-ov-file#eclipse-temurin
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - run: which java

      - uses: actions/setup-go@v5
        with:
          go-version: '^1.13.1' # The Go version to download (if necessary) and use.
      - run: go version

      - uses: nf-core/setup-nextflow@v1

      - name: Run with Docker
        run: ./run_local_docker.sh
